## this is a toml config file for server

## encode style of http request header 
enc = "utf8"

### enable https transformation
tls = false

### ssl public certificate
tlsCert = ""

### ssl private key
tlsKey = ""

### domain name of the service endpoint
domain = "example.com"

### listen port of the service
port = 8080

### dir to storage files
data = "/home/daemonw/data"

### dir to storage log files
logDir = "/home/daemonw/log"

### database config
[database]

### database port
port = 5432

### database host
host = "127.0.0.1"

### database owner
user = "postgres"

### database name

name = "go_dev"

### the password to connect database

password = "a123456"

### ssl-mode to connect

sslMode = "disable"

### cache config, default use  redis cache
[redis]

### port
port = 6379

### host
host = "127.0.0.1"

### password

password = ""

### db num

index=0

### max client connection
maxConn = 3000

### enterprise email account
[smtpServer]

account = "example@163.com"

password = "a12345678"

host = "smtp.163.com" ##163 smtp server host

port = 25  ## default 163 port
